### ISSUE TITLE
Typo in ADR post

### ISSUE THREAD

**Issue by jaredballou** [kevinjalbert/ama#2]
Hi, in https://kevinjalbert.com/start-now-architecture-decision-records/ you have the TOC generation command as `adr generate toc > ./docs/adr/README.md`, but `docs` should be `doc`.

**Comment by kevinjalbert** [comment]
Hello, @jaredballou thanks for pointing that out! I normally use the `.adr-dir` to make the default directory `docs`, as to me that sounds better (and works with existing docs directories we have at work). I guess that just snuck into the post.

If you can get around to the typo fix before I do that works :) (https://github.com/kevinjalbert/kevinjalbert.github.io/blob/real-master/source/articles/2018-01-03-start-now-architecture-decision-records.md). Otherwise I'll fix it over the weekend.

Thanks again for finding that typo. I Hope you enjoyed the post otherwise :).

**Comment by kevinjalbert** [comment]
Fixed in https://github.com/kevinjalbert/kevinjalbert.github.io/commit/c0d93d12bf07ef4b6da4c7fa92e7c7ecb6e0932e.

Thanks again for pointing it out :)
